### ISSUE TITLE
Breaks in WDIO 6: Cannot read property 'cjson:metadata' of undefined

### ISSUE THREAD

**Issue by bkrrrr** [alextiley/wdio-cucumber-json-reporter#7]
Our Project can't run after upgrading to WDIO 6.
It looks like the API has changed a bit.

**Error** 
[0-0] 2020-03-31T11:35:52.667Z ERROR @wdio/local-runner: Failed launching test session: TypeError: Cannot read property 'cjson:metadata' of undefined

Fast investigation with console.log
![image](https://user-images.githubusercontent.com/14314310/78022476-47aa9f00-7355-11ea-8257-c746ee63cde6.png)

Package.json
```"@babel/core": "^7.9.0",
    "@babel/preset-env": "^7.9.0",
    "@babel/register": "^7.9.0",
    "@ui5/cli": "^1.14.0",
    "@wdio/cli": "^6.0.8",
    "@wdio/cucumber-framework": "^6.0.8",
    "@wdio/junit-reporter": "^6.0.8",
    "@wdio/local-runner": "^6.0.8",
    "@wdio/selenium-standalone-service": "^6.0.8",
    "@wdio/spec-reporter": "^6.0.8",
    "@wdio/sync": "^6.0.8",
    "chai": "^4.2.0",
    "deepmerge": "^4.2.2",
    "eslint": "^6.8.0",
    "eslint-plugin-jsdoc": "^22.1.0",
    "npm-run-all": "^4.1.5",
    "nyc": "^15.0.0",
    "rimraf": "^3.0.2",```

**Comment by philqa** [comment]
+1. Also having this issue. It looks like the cause is the new WDIOConfig/interface. Manually maintaining a package with a fix for now.

**Comment by bkrrrr** [comment]
i just realised, this is the wrong repo; moved to https://github.com/wswebcreation/wdio-cucumberjs-json-reporter
